# Generated by Django 4.0.1 on 2023-10-20 02:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='dia',
            field=models.DateField(help_text='Introduzca una fecha', validators=[medicos.models.validar_dia]),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 a las 08:00'), ('2', '08:00 a las 09:00'), ('3', '09:00 a las 10:00'), ('4', '10:00 a las 11:00'), ('5', '11:00 a las 12:00')], max_length=10),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefono',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Su número debe estar en el siguiente formato:                     '+56 9 9999-9999'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono'),
        ),
    ]
